Reintroduce getting the conflicting entity id and the language (#361)
* Reintroduce getting the conflicting entity id and the language and test everything.
wbi_exceptions.py:
MWApiError: New attributes code, info, messages, messages_names.
get_conflicting_entity_id(), get_language(): New methods.
test_wbi_exceptions.py: Add TestCase class TestWbiExceptions and move the existing functions into it.
TestWbiExceptions:
test_modification_failed(), test_failed_save(): Add 2 assertions for the new properties.
test_modification_failed_no_dict(), test_modification_failed_no_message(), test_modification_failed_no_parameters(): New tests

* Handle DataValueCorrupt which are missing info key and other information.
wbi_exceptions.py: MWApiError:
get_conflicting_entity_id(), get_language(): Add logic to raise new exception if the information is missing.
DataValueCorrupt: New exception.

* wbi_exceptions.py: MWApiError:
get_conflicting_entity_id(), get_language(): Raise IndexError with the whole error dict.

* wbi_exceptions.py: MWApiError:
get_language(): Raise NonExistentEntityError if not found.

* Optimize properties to return list instead of str

Optimize get_conflicting_entity_id and get_language from wbi_exceptions to return a List of str or None

* Update wbi_exceptions.py

Remove unused attribute

* Update wikibaseintegrator/wbi_exceptions.py

Co-authored-by: Christian Clauss <cclauss@me.com>

* Replace "return None" to empty List

* Unused Exception

Removed for the time being.

* Use plural form

Co-Authored-By: Christian Clauss <cclauss@me.com>

Co-authored-by: Myst <1592048+LeMyst@users.noreply.github.com>
Co-authored-by: Christian Clauss <cclauss@me.com>